#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  Intersys_facebook.py
#
#  Copyright 2017 AVELAZCX <aldo.alfonsox.velasco.meza@intel.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.


import datetime, time, unittest,HtmlTestRunner,xmlrunner
from selenium import webdriver
from colorama import init,Fore, Back, Style
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.common.exceptions import NoSuchElementException



class ItersysFacebook(unittest.TestCase):
    init(autoreset=True)
    print(Back.GREEN + Fore.WHITE + "\n<================================ INTERSYS FACEBOOK =================================>")
    print(Fore.GREEN + "-------------------------------------------------------------------------------")
    print(Fore.MAGENTA + """                        TEST CASE #2
                """)
    def setUp(self):

        #Go to https://www.facebook.com/   
        print ("TEST IN PROGRESS")
        self.driver = webdriver.Chrome("C:\Python27\dr_src\chromedriver.exe")
        self.driver.implicitly_wait(30)
        self.driver.get("https://www.facebook.com/")
        self.driver.maximize_window()
        self.verificationErrors = []
        self.accept_next_alert = True


##### CONECTA AL WEB SERVER DE SELENIUM PARA TRABAJO REMOTO #####

        # self.driver = webdriver.Remote(
        #    command_executor='http://127.0.0.1:4444/wd/hub',
        #    desired_capabilities=DesiredCapabilities.CHROME)
        # self.driver.get("http://192.168.1.254")
        # self.driver.implicitly_wait(30)

    def test_1_Capture_a_valid_login(self):
                 #Capture a valid login
                 driver = self.driver
                 try:
                     self.driver.find_element_by_id('email').send_keys("aldovelmeza@gmail.com")
                     time.sleep(2)
                 except NoSuchElementException:
                     self.assertTrue(self.search_field, "Fail.... ")
                     st = datetime.datetime.fromtimestamp(time.time()).strftime("%Y-%m-%d %H;%M")
                     file_name = "TC1_Capture a valid login" + st + ".png"
                     driver.save_screenshot(file_name)
                     raise
                 finally:
                     print("Fail")

    def test_2_Capture_invalid_password(self):
                 #Capture invalid password
                 driver = self.driver
                 try:
                     self.driver.find_element_by_id('pass').send_keys("invalidPass@123")
                     time.sleep(5)
                 except NoSuchElementException:
                     self.assertTrue(self.search_field, "Fail.... ")
                     st = datetime.datetime.fromtimestamp(time.time()).strftime("%Y-%m-%d %H;%M")
                     file_name = "TC2_Capture invalid password" + st + ".png"
                     driver.save_screenshot(file_name)
                     raise
                 finally:
                     print("Fail")

    def test_3_Login_submit(self):
                 #Hit the log in button and wait for the response
                 driver = self.driver
                 try:
                     self.driver.find_element_by_id('email').send_keys("aldovelmeza@gmail.com")
                     time.sleep(2)
                     self.driver.find_element_by_id('pass').send_keys("invalidPass@123")
                     time.sleep(5)
                     self.search_field = self.driver.find_element_by_xpath('//*[@id="u_0_t"]').submit()
                     time.sleep(8)
                     #self.search_field = self.driver.find_element_by_id('not_me_link').click()
                     #time.sleep(13)        
                 except NoSuchElementException:
                     self.assertTrue(self.search_field, "Fail.... ")
                     self.assertequal(self.company, compan, "Error not equal............ ")
                     st = datetime.datetime.fromtimestamp(time.time()).strftime("%Y-%m-%d %H;%M")
                     file_name = "TC3_Login_Submit" + st + ".png"
                     driver.save_screenshot(file_name)
                     raise
                 finally:
                     print("Fail")

    def test_4_Click_Not_me(self):
                 #Click Not me
                 driver = self.driver
                 try:
                     self.driver.find_element_by_id('email').send_keys("aldovelmeza@gmail.com")
                     time.sleep(2)
                     self.driver.find_element_by_id('pass').send_keys("invalidPass@123")
                     time.sleep(5)
                     self.search_field = self.driver.find_element_by_xpath('//*[@id="u_0_t"]').submit()
                     time.sleep(8)
                     self.search_field = self.driver.find_element_by_id('not_me_link').click()
                     time.sleep(13)        
                 except NoSuchElementException:
                     self.assertTrue(self.search_field, "Fail.... ")
                     self.assertequal(self.company, compan, "Error not equal............ ")
                     st = datetime.datetime.fromtimestamp(time.time()).strftime("%Y-%m-%d %H;%M")
                     file_name = "TC4_Click_not_me" + st + ".png"
                     driver.save_screenshot(file_name)
                     raise
                 finally:
                     print("Fail")


    def is_element_present(self, how, what):
        try:
            self.driver.find_element(by=how, value=what)
        except NoSuchElementException as e:
            return False
        return True


    def is_alert_present(self):
        try:
            self.driver.switch_to.alert()
        except NoAlertPresentException as e:
            return False
        return True

    def close_alert_and_get_its_text(self):
        try:
            alert = self.driver.switch_to.alert()
            alert_text = alert.text
            if self.accept_next_alert:
                alert.accept()
            else:
                alert.dismiss()
            return alert_text
        finally:
            self.accept_next_alert = True


    def tearDown(self):
        self.driver.quit()
        self.assertEqual([], self.verificationErrors)

if __name__ == '__main__':
    print(Fore.YELLOW +"\t\t ==== Test in progress ====\n")
    unittest.main(testRunner=HtmlTestRunner.HTMLTestRunner(output='intersys_facebook'),failfast=False, buffer=False, catchbreak=False,verbosity=2)
    testRunner=xmlrunner.XMLTestRunner(output='facebook-reports')
